version: "3"
services:
  python_question_bank:
    build: ./QB
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - LANGUAGE=Python

  c_question_bank:
    build: ./QB
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - LANGUAGE=C

  test_manager:
    build: ./TM
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - ENV=docker
      - WAIT_HOSTS=python_question_bank:8080, c_question_bank:8081